### PR TITLE
Capistrano recipe

### PR DESCRIPTION
**Pull request by manuelvanrijn**
A simple recipe that automatically checks for vulnerabilities before a `cap deploy`

### CODE REVIEW

**Comment by mackuba** [comment]
Good idea, thanks!

**Comment by mxwimdu** [comment]
:+1:

**Comment by manuelvanrijn** [comment]
here's an updated version

**Comment by mackuba** [comment]
Man, what did you do with that branch? It looks like you've merged the branch into itself, which created two separate threads with the same set of commits running in parallel... I haven't seen that before ;)

Anyway, I've just rebased the commits on top of master to make things clean.

Also, I've changed the task to run _after_ `deploy:update_code` - it doesn't make much sense to test code before you download the latest version... :)

**Comment by mackuba** [comment]
No, wait, that doesn't make sense, holepicker is run here _locally_, not on the server, so it doesn't matter if the code was updated there, it should probably be run as soon as possible. I'll revert that change.

**Pull request closed without merging**
