### PR TITLE
Adding latest versions for Devise branches 1.3, 1.2 and 1.1 to remove false positives

### PR DESCRIPTION
**Pull request by pascalvanhecke**
(added all versions that should be included)

### CODE REVIEW

**Comment by mackuba** [comment]
Thanks for info. Actually, if 1.3.x and below are not vulnerable as the announcement says, it should be ok to just add "1.2.0" and "1.1.0" (and "1.3.0") there, right? Otherwise people with e.g. 1.1.8 will still get a warning.

**Comment by pascalvanhecke** [comment]
You are right there! Did not think it through.

**Comment by pascalvanhecke** [comment]
Hi @jsuder, is there a reason why you do not accept the pull request?  Do you think there are disadvantages of this method?  I think it is preferable to add these pre 1.4 branches instead of excluding devise from holepicker runs alltogether?

**Comment by mackuba** [comment]
Sorry, forgot about this.

I've removed 1.1 because @josevalim says there in the comments that he didn't even look at it because it's really not recommended to use it anymore.

And I've used 1.2.0 and 1.3.0 because of the way I wrote the version comparator - if it sees version 1.n as fixed then it assumes that 1.x are ok for any x >= n, so 1.4 and 1.5 would be matched too.

**Pull request closed without merging**
